// ICAO → LiveATC Icecast mount point mapping.
// Loaded from data/liveatc-feeds.json (generated by crawl-liveatc.ts).
// Falls back to empty map if the file is missing.

import * as fs from 'fs';
import * as path from 'path';

interface LiveAtcFeed {
  name: string;
  mount: string;
  pls_url: string;
  dedicated: boolean;
}

interface OutputJson {
  generated_at: string;
  airports: Record<string, { feeds: LiveAtcFeed[] }>;
}

function loadMounts(): Map<string, { mount: string; dedicated: boolean }> {
  const map = new Map<string, { mount: string; dedicated: boolean }>();
  const jsonPath = path.join(__dirname, '../../data/liveatc-feeds.json');

  try {
    if (!fs.existsSync(jsonPath)) return map;

    const data: OutputJson = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));

    for (const [icao, entry] of Object.entries(data.airports)) {
      if (!entry.feeds || entry.feeds.length === 0) continue;

      // Prefer dedicated ATIS feeds; fall back to first available
      const dedicated = entry.feeds.find((f) => f.dedicated);
      const best = dedicated || entry.feeds[0];

      map.set(icao, { mount: best.mount, dedicated: best.dedicated });
    }
  } catch {
    // Silently fall back to empty map if file is missing or corrupt
  }

  return map;
}

export const LIVEATC_MOUNTS = loadMounts();
